### ISSUE TITLE
I got this error, you can help me

### ISSUE THREAD

**Issue by duchuAz** [zyairelai/futures-omax#8]
Traceback (most recent call last):
  File "run.py", line 12, in <module>
    if binance_futures.position_information()[0].get('marginType') != "cross": binance_futures.change_margin_to_CROSSED()
  File "/home/ubuntu/futures-omax/binance_futures.py", line 18, in position_information
    def position_information()      : return client.futures_position_information(symbol=config.pair, timestamp=get_timestamp())
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 5070, in futures_position_information
    return self._request_futures_api('get', 'positionRisk', True, data=params)
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 222, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 180, in _request
    kwargs['data']['signature'] = self._generate_signature(kwargs['data'])
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 135, in _generate_signature
    m = hmac.new(self.API_SECRET.encode('utf-8'), query_string.encode('utf-8'), hashlib.sha256)
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by zyairelai** [comment]
This is an solved issue. Please refer to https://github.com/zyairelai/futures-omax/issues/1#event-4325774265
